In [22]:
#import libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

In [23]:
#load the dataset
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#set names of the colums
columnNames = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
#create and set data variable
data = pd.read_csv(url, names=columnNames)

In [24]:
#preprocess the Data
x = data.drop('class', axis=1)
y = data['class']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [25]:
#train the k-NN model
#amount of nearest neighbours set
#k = 3 
knn_classifier = KNeighborsClassifier(n_neighbors=k)
knn_classifier.fit(x_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [26]:
#predictions and evaluate model
y_pred = knn_classifier.predict(x_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


In [27]:
#calculate confusion matrix and f1 score
confusion_mat = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
print("Confusion Matrix:\n", confusion_mat)
print(f"F1 Score: {f1:.2f}")

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
F1 Score: 1.00
